### ISSUE TITLE
watermark for video on top right

### ISSUE THREAD

**Issue by Qasem-h** [blazeroot/videoshrimp#3]
Hi 
how i can use watermark command with video convert command ?

**Comment by Qasem-h** [comment]
@blazeroot

**Comment by blazeroot** [comment]
Hi @Qasem-h,

to add watermark you should use ffmpeg filter option as described [here](https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/watermarks).

**Comment by Qasem-h** [comment]
@blazeroot Thanks for replay but im tried to use it but i cant ! i dont know what uis the problem but not work for me 
This is my app worker 

``` ruby
class Mp4VideoEncoder
  include Sidekiq::Worker

  def perform(video_id)
    video = Video.find(video_id)
    path = video.video_file.path
    output = "/tmp/#{Time.now.getutc.to_f.to_s.delete('.')}.mp4"
    _command = `/home/qasem/bin/ffmpeg -i #{path} -i watermarklogo.png -filter_complex \
"overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -codec:a -f mp4 -vcodec h264 -acodec aac -strict -2 #{output}`
    if $?.to_i == 0
      video.mp4_file = File.open(output, 'r')
      video.save
      FileUtils.rm(output)
    else
      raise $?
    end
  end
end
```

again thanks for reply

**Comment by blazeroot** [comment]
@Qasem-h could you share the error you're getting, please?

**Comment by Qasem-h** [comment]
@blazeroot  Thanks for reply 
this is my error : 

```
2016-06-27T15:37:32.933Z 20280 TID--9ke1hm Mp4VideoEncoder JID-1df520c436523cc2fb179030 INFO: start
ffmpeg version N-80388-gfd1d84b Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  configuration: --prefix=/home/qasem/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/qasem/ffmpeg_build/include --extra-ldflags=-L/home/qasem/ffmpeg_build/lib --bindir=/home/qasem/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 46.100 / 57. 46.100
  libavformat    57. 38.101 / 57. 38.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.101 /  6. 46.101
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/qasem/_video/public/uploads/video/video_file/13/dec6a9dde4d67d2225bff39a8760a5084061032-270p__80845.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    comment         : http://www.aparat.com/iran4moderntalking
  Duration: 00:01:22.04, start: 0.000000, bitrate: 471 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 418 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Input #1, image2, from '/home/qasem/_video/public/wm.png':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 662 kb/s
    Stream #1:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 63x30 [SAR 1:1 DAR 21:10], 25 tbr, 25 tbn, 25 tbc
[NULL @ 0xaa0a5e0] Unable to find a suitable output format for 'mp4'
mp4: Invalid argument
2016-06-27T15:37:33.014Z 20280 TID--9ke1hm Mp4VideoEncoder JID-1df520c436523cc2fb179030 INFO: fail: 0.081 sec
2016-06-27T15:37:33.014Z 20280 TID--9ke1hm WARN: {"class":"Mp4VideoEncoder","args":[13],"retry":true,"queue":"default","jid":"1df520c436523cc2fb179030","created_at":1467041683.247223,"enqueued_at":1467041852.9311557,"error_message":"exception class/object expected","error_class":"TypeError","failed_at":1467041683.251145,"retry_count":3,"retried_at":1467041853.0121906}
2016-06-27T15:37:33.014Z 20280 TID--9ke1hm WARN: TypeError: exception class/object expected
2016-06-27T15:37:33.015Z 20280 TID--9ke1hm WARN: /home/qasem/_video/app/workers/mp4_video_encoder.rb:16:in `raise'
/home/qasem/_video/app/workers/mp4_video_encoder.rb:16:in `perform'
/home/qasem/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in `execute_job'
```

and this is my mp4videoencoder

``` Ruby
class Mp4VideoEncoder
  include Sidekiq::Worker

  def perform(video_id)
    video = Video.find(video_id)
    path = video.video_file.path
    wm = Rails.root.join("public", "wm.png")
    output = "/tmp/#{Time.now.getutc.to_f.to_s.delete('.')}.mp4"
    _command = `/home/qasem/bin/ffmpeg -i #{path} -i #{wm} -filter_complex \
"overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -codec:a -f mp4 -vcodec h264 -acodec aac -strict -2 #{output}`
    if $?.to_i == 0
      video.mp4_file = File.open(output, 'r')
      video.save
      FileUtils.rm(output)
    else
      raise $?
    end
  end
end


```
